spring.application.name=ticketing-system
# --- ADATBÁZIS KAPCSOLAT ---
# A JDBC (Java Database Connectivity) URL-je, ami mutat a mi Docker adatbázisunkra
spring.datasource.url=jdbc:postgresql://db/ticketing
spring.datasource.username=admin
spring.datasource.password=secret

# --- JPA / HIBERNATE BEÁLLÍTÁSOK ---
# A dialektus, hogy a Hibernate tudja, milyen "tájszólásban" kell SQL-t generálnia (PostgreSQL)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ez egy nagyon fontos beállítás! Ez mondja meg a Hibernate-nek,
# hogy automatikusan hozza létre (update) a táblákat az adatbázisban a Java osztályaink alapján.
spring.jpa.hibernate.ddl-auto=update

# Ez arra jó, hogy a konzolon (a fejlesztői környezet alján) lássuk a generált SQL parancsokat.
# Nagyon hasznos hibakeresésnél!
spring.jpa.show-sql=true

${KÖRNYEZETI_VÁLTOZÓ:alapértelmezett_érték}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

